model:
  type: Bert
dataset:
  path: glue
  name: sst2
  data_dir:
  data_files:
  text_key: sentence
abspath: /home/jovyan/examples/examples/pytorch/MPhil_BO
aug: sst2
per_device_train_batch_size: 64
per_device_eval_batch_size: 128
epoch: 10
lr: 4e-5
max_seq_length: 128
n_aug: 8
alpha: 0.05
sparsity: 500
class_imbalance: 0.75
num_classes: 2
method: taa
topN: 1
seed: 42
trail: 1
num_search: 200
num_gpus: 4
num_cpus: 40

